export const rows = [
    {   
        id: 1, 
        lastName: 'Snow', 
        firstName: 'Jon',
        age: 35,
        email:'jonsnow@gmail.com',
        designation: 'Frontend Developer',
        salary:20000,
    },
    {   
        id: 2, 
        lastName: 'Snow', 
        firstName: 'Jon',
        age: 35,
        email:'jonsnow@gmail.com',
        designation: 'Frontend Developer',
        salary:20000,
    },
    {   
        id: 3, 
        lastName: 'Snow', 
        firstName: 'Jon',
        age: 35,
        email:'jonsnow@gmail.com',
        designation: 'Frontend Developer',
        salary:20000,
    },
    {   
        id: 4, 
        lastName: 'Snow', 
        firstName: 'Jon',
        age: 35,
        email:'jonsnow@gmail.com',
        designation: 'Frontend Developer',
        salary:20000,
    },
    {   
        id: 5, 
        lastName: 'Snow', 
        firstName: 'Jon',
        age: 35,
        email:'jonsnow@gmail.com',
        designation: 'Frontend Developer',
        salary:20000,
    },
    {   
        id: 6, 
        lastName: 'Snow', 
        firstName: 'Jon',
        age: 35,
        email:'jonsnow@gmail.com',
        designation: 'Frontend Developer',
        salary:20000,
        },
      ]