export const userData = [
    {   
        id: 1, 
        lastName: 'Maharjan', 
        firstName: 'Joel',
        age: 23,
        email:'joelmaharjan23@gmail.com',
        designation: 'Frontend Developer',
        salary:40000,
    },
    {   
        id: 2, 
        lastName: 'Singh', 
        firstName: 'Rubit',
        age: 25,
        email:'rubitsingh@gmail.com',
        designation: 'Backend Developer',
        salary:25000,
    },
    {   
        id: 3, 
        lastName: 'Rumba', 
        firstName: 'Manish',
        age: 21,
        email:'Manishrumba@gmail.com',
        designation: 'Python Developer',
        salary:26000,
    },
    {   
        id: 4, 
        lastName: 'Thokar', 
        firstName: 'Kiran',
        age: 31,
        email:'kiranthokar@gmail.com',
        designation: 'Frontend Developer',
        salary:34000,
    },
    {   
        id: 5, 
        lastName: 'Basnet', 
        firstName: 'Naran',
        age: 24,
        email:'naranbasnet@gmail.com',
        designation: 'Java',
        salary:20000,
    },
    {   
        id: 6, 
        lastName: 'K.C.', 
        firstName: 'Samrat',
        age: 21,
        email:'samratkc@gmail.com',
        designation: 'Project Manager',
        salary:98000,
        },
      ]